### ISSUE TITLE
Use relative paths for script definition within tests

### ISSUE THREAD

**Issue by drpatelh** [askimed/nf-test#100]
Hola! I am trying to create a standardised directory structure to ship nf-test with modules in a stand-alone way to make them easier to share.

For example, if we have the module structure here:

```
.
├── modules
│   ├── local
│   │   ├── my_module
│   │   │   ├── main.nf
│   │   │   └── tests
│   │   │       ├── main.nf.test
│   │   │       └── main.nf.test.snap
```

What I would like to do is have a relative path for the `script` definition within `main.nf.test`. e.g.

```
nextflow_process {
    name "Test Process MY_MODULE"
    script "../main.nf"
    process "MY_MODULE"
    tag "my_module"
}
```

This is the `nf-test.config` we are currently using:

```
config {
    // location for all nf-tests
    testsDir "."

    // nf-test directory including temporary files for each test
    workDir ".nf-test"

    // location of library folder that is added automatically to the classpath
    libDir "lib/"

    // location of an optional nextflow.config file specific for executing tests
    configFile "nextflow.config"

    // run all test with the defined docker profile from the main nextflow.config
    profile ""
}
```

Is it possible to use relative paths within the `script` definition? If not, this would be really useful for us to bundle tests with modules / subworkflows / workflows.

Please let me know if you need any more info from me! Thanks in advance!

**Comment by lukfor** [comment]
Hi Harshil, thanks for the feedback. I agree, relative paths make it easier to share and copy modules.
We implemented a first approach in #103 and the functionality will be available in the next release 👍
