### ISSUE TITLE
`--replaceSnapshot` option

### ISSUE THREAD

**Issue by sateeshperi** [askimed/nf-test#104]
The current behavior of `--updateSnapshot` method appends to an existing snapshot which when the assertions change the snapshot might not be representative of the final set of assertions in the test file. Right now we can delete the snap and re-create it but, was wondering if we could have this option to replace handy too ? Would love to hear your thoughts.

**Comment by Emiller88** [comment]
I think this should just be the behavior of `--udpateSnapshot` personally.

If you wanted to be chaotic, make `--updateSnapshot` delete the snapshot, and create a new one, and `--update-snapshot` continue with the usual behavior.

**Comment by lukfor** [comment]
Hi Sateesh, thanks for the feedback and also for promoting nf-test 🙏

I am not sure if I understand the difference between `--updateSnapshot` and `--replaceSnapshot`. Could you please provide an example of an nf.test file where you can see this (expected vs. observed behavior)?

Thanks!

**Comment by sateeshperi** [comment]
Hey Sure! here are the details.

This [test file](https://github.com/nf-core/fetchngs/blob/2011565650099d464a19971d35b292500750c201/workflows/sra/tests/skip_fastq.nf.test) was how I originally had assertions for published files for the fetchngs pipeline and its [snap](https://github.com/nf-core/fetchngs/blob/2011565650099d464a19971d35b292500750c201/workflows/sra/tests/skip_fastq.nf.test.snap)

Later Harshil updated the [test file](https://github.com/nf-core/fetchngs/blob/dev/workflows/sra/tests/sra_skip_fastq_download.nf.test) and the [snapshots](https://github.com/nf-core/fetchngs/blob/dev/workflows/sra/tests/sra_skip_fastq_download.nf.test.snap) to replace the assertions for published files with assertion for `snapshot(process.out).match()` thinking it will capture all the output files without having to specify them manually as it does for a process.out which has specified emits. Obviously that didn't work in a pipeline scope but, it added the following empty block to the snapshot and every time the test was run we thought that the test was passing as the updated assertion was just checking for the empty map in the snapshot, finding it there making the test a success.

```
{
    "Parameters: --skip_fastq_download": {
        "content": [
            {
                
            }
        ],
        "timestamp": "2023-08-18T00:30:59+0000"
    }
}
```

Expected behaviour of `--updateSnapshot` - to have repalced the entire  contents of the snapshot instead of appending to it

I hope that makes it a bit more clear

**Comment by lukfor** [comment]
Thanks! That helps a lot 👍

I see, this happens if you change the name of the test. In that case it is appended and not replaced. We will think about how to handle that case.

In addition, we will remove the `process` object from `nextflow_pipeline` in order to see an error instead of getting an empty `out` map.

**Comment by lukfor** [comment]
One possible alternativ approach:
- on run test we count witch key in the snap file was used by `toMatch()` and print a list of obsolete snapshots (=keys that are only present in the snap file)
- When running with` --updateSnapshot` we could remove the obsolete snapshots from the snap file
- frameworks like jest are using a similar strategy

**Comment by sateeshperi** [comment]
that sounds good to me!

**Comment by Emiller88** [comment]
> When running with --updateSnapshot we could remove the obsolete snapshots from the snap file
Could this be a flag? `--wipeSnapshot`?
