### ISSUE TITLE
Verbose option

### ISSUE THREAD

**Issue by maxulysse** [askimed/nf-test#111]
I notice that Nextflow is run in quiet mode, is there any way to disable that?

**Comment by maxulysse** [comment]
I'm sure it could be useful when debugging

**Comment by lukfor** [comment]
I think the`--debug` flag starts nextflow without the silent mode.

**Comment by antunderwood** [comment]
+1 I would find this very helpful

**Comment by lukfor** [comment]
The `--verbose` option was added in https://github.com/askimed/nf-test/commit/9b569017b9af83892e361ec3b9936207eb56df5d and produces the following output:

<img width="1403" alt="Screenshot 2023-10-07 at 09 42 28" src="https://github.com/askimed/nf-test/assets/210220/904ae606-dd24-4437-85d8-4ad12af66ccb">
