### ISSUE TITLE
Testing individual processes within a pipeline

### ISSUE THREAD

**Issue by vasquini** [askimed/nf-test#14]
We know a pipeline can be tested, and so can individual processes in separate module files. But can I get an individual test for each process within a pipeline? We have a large nextflow script we were trying to test. The processes are not in individual files, but we want to have an individual test for each.

**Comment by vasquini** [comment]
(base) [suj7@login02 Dev-micropipe4]$ nf-test generate process main.nf

🚀 nf-test 0.5.1
https://code.askimed.com/nf-test
(c) 2021 - 2022 Lukas Forer and Sebastian Schoenherr


Load source file '/scicomp/home-pure/suj7/Dev-micropipe4/main.nf'
Skipped. More then one process definition found. Please create one file per process.

SUCCESS: Generated 0 test files.

(base) [suj7@login02 Dev-micropipe4]$

**Comment by lukfor** [comment]
Thanks for reporting that issue!

We updated the `generate process` command and it supports now files with multiple processes. It creates one test file per process.

This functionality is available in the next release.
