### ISSUE TITLE
relative path input file create symlinks use $launchDir not $projectDir? 

### ISSUE THREAD

**Issue by mcolpus** [askimed/nf-test#140]
When following the nf-test tutorial (https://code.askimed.com/nf-test/docs/getting-started/) the test fails with `The file [transcriptome.fa] provided for the transcriptome does not appear to exist.`

The input file to use in testing is defined
`input[0] = file("test_data/transcriptome.fa")`

When I go to the test work directory and list the files I get:
```
drwxr-xr-x 2 mcolpus mcolpus  4096 Oct 23 16:53 .
drwxr-xr-x 3 mcolpus mcolpus  4096 Oct 23 16:53 ..
-rw-r--r-- 1 mcolpus mcolpus     0 Oct 23 16:53 .command.begin
-rw-r--r-- 1 mcolpus mcolpus   903 Oct 23 16:55 .command.err
-rw-r--r-- 1 mcolpus mcolpus   903 Oct 23 16:55 .command.log
-rw-r--r-- 1 mcolpus mcolpus     0 Oct 23 16:53 .command.out
-rw-r--r-- 1 mcolpus mcolpus 10338 Oct 23 16:53 .command.run
-rw-r--r-- 1 mcolpus mcolpus    60 Oct 23 16:53 .command.sh
lrwxrwxrwx 1 mcolpus mcolpus   105 Oct 23 16:53 transcriptome.fa -> /home/mcolpus/nf-test-examples/.nf-test/tests/66eba6f9777daa4fc08e7efaabe3a486/test_data/transcriptome.fa
```

And so this causes the process to fail as transcriptome.fa can't be found.

This can be fixed by changing to:
`input[0] = file("$projectDir/test_data/transcriptome.fa")`
But I don't know if there is a config option I have wrong instead?

I'm using version:
```
🚀 nf-test 0.8.1
https://code.askimed.com/nf-test
(c) 2021 - 2023 Lukas Forer and Sebastian Schoenherr

Nextflow Runtime:
    > 
      N E X T F L O W
      version 22.04.5 build 5708
      created 15-07-2022 16:09 UTC (17:09 BST)
      cite doi:10.1038/nbt.3820
      http://nextflow.io
```

**Comment by lukfor** [comment]
Thanks Matthew! Yes, this is caused by a change in 0.8. We will update the documentation.
