### ISSUE TITLE
Bug/improvement: base `md5` checksum of gzipped files on file content, not file

### ISSUE THREAD

**Issue by koenbossers** [askimed/nf-test#141]
md5 hashes are not a reliable way to test `.gz` files produced in `conda` versus `docker` or `singularity` runs. While the contents of the .`gz` files match (e.g. as determined by `zdiff`), the files themselves are different if md5sums are calculated. This is **not** due to a bug in nf-test, but due to the fact that differences exist in the low-level compression algorithms used by `conda`, which causes md5 checkum differences while the content is the same.

This means essentially also that the snapshot function, while fantastic, cannot be used in all circumstances. E.g. in the nf-core github CI pipeline, you now get checksum fails that do not reflect differences in the `.gz` files. See for example the following pull request: https://github.com/nf-core/modules/pull/4185

A solution can be to incorporate code in nf-test that, when it encounters a .gz file, creates a md5 checksum based on the actual file contents, NOT the file itself. Workarounds such as using `.linesGzip()`  to check for matching file contents either create huge `.snap files` (because it will contain the entire list of lines as strings in the .snap) or, when testing only subsets of lines, risk missing differences that should be detected.

A possible solution can be to adjust the following function by adding a case for `.gz` files, decompress them as a stream, and return the md5 of that stream.

https://github.com/askimed/nf-test/blob/a55678ded549aaf1d6f8cc58830e6b3b43649603/src/main/java/com/askimed/nf/test/util/FileUtil.java#L105-L115

**Note**: this will break existing snapshots that contain `.gz` files

**Comment by lukfor** [comment]
I merged the PR from Koen! 👍Thanks!
