### ISSUE TITLE
nf-test should not generate a snapshot if a test fails

### ISSUE THREAD

**Issue by sateeshperi** [askimed/nf-test#147]
When initially creating a snapshot, if the test fails, a snapshot is still created regardless. It would be nice if this wasn't the case. Would be interested to hear author's thoughts on this. Thank you

**Comment by lukfor** [comment]
Thanks! We ran into the same problem when using `assertAll()`, as all asserts are executed even if the previous assert fails.

One solution is to use them without `assertAll`, and the test stops immediately when the first assert fails:

```java
assert workflow.success
assert(snapshot(...).match())
```

Another possibility is to extract the `assert workflow.success` from the `assertAll`:

```java
assert workflow.success
assertAll {
   ...
   assert(snapshot(...).match())
   ...
}
```

**Comment by sateeshperi** [comment]
makes sense....thanks for pointing out.
