### ISSUE TITLE
[Feature] Provide a method to compare hash of compressed content only

### ISSUE THREAD

**Issue by Midnighter** [askimed/nf-test#157]
Last request for today, I promise 😉.

There are many tools that provide gzip-compressed output which is convenient to save storage space. However, a proportion of them do not exclude the modification timestamp in the gzip header. This is usually outside the control of a pipeline author. It would be extremely helpful to have a convenient `path` method like `.md5` that only hashes the compressed content and ignores the header with the modification timestamp.

I don't know if there is an efficient way to do so, but it can certainly be done by decompressing the content.

**Comment by lukfor** [comment]
Thanks for your feedback! 👍 For gz files, this was implemented in #144 and is now available in v0.8.2
