### ISSUE TITLE
Assertions for images such as PNG, JPEG

### ISSUE THREAD

**Issue by GallVp** [askimed/nf-test#159]
Hi Team

Thank you for creating an excellent framework.

I was wondering if there is way to compare images across process runs. md5 based snapshot matching might fail due to meta-data differences with same image data. I have observed this when comparing md5's of images created with the same data using the same tool under Docker vs Conda.

Thank you!

**Comment by lukfor** [comment]
Thanks.

I just found this library: https://romankh3.github.io/image-comparison/

This could be a good start to write a `nft-images` plugin.

**Comment by lukfor** [comment]
Issue #33 contains the same request. I will close this one.
