### ISSUE TITLE
nf-test script should respect JAVA_HOME and JAVA_CMD environment variables

### ISSUE THREAD

**Issue by ahvigil** [askimed/nf-test#163]
nextflow has [logic to find a desired `java`](https://github.com/nextflow-io/nextflow/blob/832bff241f64cc3ce9b4cdc794a58d1664c0933c/nextflow#L263-L282) via standard environment variables like `JAVA_HOME` and `JAVA_CMD` (and also a nextflow specific `NXF_JAVA_HOME`). nf-test currently just uses whichever `java` is on PATH. This can cause `nextflow` and `nf-test` to use different javas. In my case this leads to an error because nf-test tries to use a system java that is way older than the java we use with nextflow via JAVA_HOME:
```
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/askimed/nf/test/App : Unsupported major.minor version 52.0
```

It would be nice if nf-test used the same/similar logic as nextflow to find the right java instance.

**Comment by lukfor** [comment]
Thanks. This is implemented in #171 and is available in the next release.
