### ISSUE TITLE
[Docs] Broken link for navigating to getting started

### ISSUE THREAD

**Issue by ometa-evan** [askimed/nf-test#182]
The link to the "Getting started" page is incorrect and results in a 404 error.

https://github.com/askimed/nf-test/blob/552af89191fa0723b9bda3dc1688f1497c7037bb/docs/installation.md?plain=1#L44

The link generated from this: https://www.nf-test.com/installation/getting-started.md (404 error page)

I think this should be:

```md
Now you are ready to write your [first testcase](docs/getting-started.md). 
```

**Comment by lukfor** [comment]
Thanks! 🙏 Broken links are fixed. 👍
