### ISSUE TITLE
Support of easy reading of VCF files

### ISSUE THREAD

**Issue by byb121** [askimed/nf-test#19]
Hi, it would be really useful if nf-test can read VCF files easily to a structural data class. I think something similar to the JSON extension will be sufficient, e.g.:

```groovy
def mutation_list = path(process.out.out_ch.get(0)).vcf
mutation_list.each { v ->
 assert v.chr == 'chr10'
}
```

A quick google search returns me this lib ([Groovy NGS Utils](https://github.com/ssadedin/groovy-ngs-utils)), which might be useful for the implementation.

**Comment by lukfor** [comment]
This is now implemented in the nft-vcf plugin: https://github.com/seppinho/nft-vcf/
