### ISSUE TITLE
Support of easy reading of FASTA files

### ISSUE THREAD

**Issue by byb121** [askimed/nf-test#20]
Similar to other file formats, it can be useful for nf-test to support FASTA files, so that FASTA files can be compared agnostic to line wrapping width, e.g.:

```bash
$ cat fasta.1.txt
> seq1
AGTACGTAGTAGCTGCTGCTACGTGCGCTAGCTAGTACGTCA
CGACGTAGATGCTAGCTGACTCGATGC
> seq2
CGATCGATCGTACGTCGACTGATCGTAGCTACGTCGTACGTA
GCATCGTCAGTTACTGCATGCTCG
$ cat fasta.2.txt
> seq1
AGTACGTAGTAGCTGCTGCTACGTGCGCTAGCTAGTACGTCACGACGTAGATGCTAGCTGACTC
GATGC
> seq2
CGATCGATCGTACGTCGACTGATCGTAGCTACGTCGTACGTAGCATCGTCAGTTACTGCATGCT
CG

# in nf-test
# assume path.fasta returns a map with sequence ids as kyes and sequences as values
assert path("fastq.1.txt").fasta == path("fastq.2.txt").fasta
```

It'll be more convinient if it can support gzipped FASTA files.

**Comment by lukfor** [comment]
Hi, I like the idea with the map! I started a new branch and implemented a simple FASTA reader 👍

**Comment by aaron-fishman-achillestx** [comment]
Nice! I added some comments. I think @byb121  will be doing some testing and will feedback on bugs etc.

**Comment by lukfor** [comment]
This is now integrated as a plugin. See https://code.askimed.com/nf-test/assertions/fasta/

Thanks @aaron-fishman-achillestx  and @byb121 for your help and efforts!
