### ISSUE TITLE
Conda environment reuse

### ISSUE THREAD

**Issue by LouisLeNezet** [askimed/nf-test#210]
Hi,
I've stumble on the following behaviour recently.
When doing multiple test for a module with a conda profile. The nf-test seems to create a new conda environment for each test.
Would it be possible to reuse the same environment ?
The environments or containers (singularity, docker) could be created in the folder of the .nf-test with a hash code and reuse if the hash didn't change.
This would allow faster tests.

**Comment by nh13** [comment]
This would be helpful iterating on tests too.

**Comment by lukfor** [comment]
Thanks! I will close this issue. Please refer to issue #231 for further discussions and updates.
