### ISSUE TITLE
Problem running new version of nft-bam: 3.0.0

### ISSUE THREAD

**Issue by maxulysse** [askimed/nf-test#225]
I ran into this error:
`Error: Syntax errors in nf-test config file: java.lang.RuntimeException: Plugin'nft-bam' found, but version 0.3.0 not found.`

After some exploration and debugging with @nvnieuwk, we found out the issue:
removing the json in `.nf-test/plugins/` did the trick, and the installation and execution of test with plugin was successful.

**Comment by lukfor** [comment]
Thanks. Yes, I know this is not yet super user-friendly. I will try to find a better solution (e.g., downloading the new JSON file when the version is not found locally).

Instead of deleting the JSON file manually, `nf-test update-plugins` should do the same.

**Comment by maxulysse** [comment]
oh, that's good to know

**Comment by maxulysse** [comment]
Some more explanation in docs would be more than enough actually
