### ISSUE TITLE
no valid tests found - v 0.9.0

### ISSUE THREAD

**Issue by nschcolnicov** [askimed/nf-test#245]
When running an nf-test on github CI, I see that the test runs, but then it crashes raising the error "no valid tests found". When running the same command on the cloned repo it runs through without any issues.

Error log:
![image](https://github.com/user-attachments/assets/41ad14aa-51b9-456e-973c-76f73bdf1d8c)

Running in the cloned repo:
![image](https://github.com/user-attachments/assets/c3362dc6-205d-4edb-af64-53ebf5348bac)

PR where the issue is happening:
https://github.com/nf-core/demultiplex/pull/253

**Comment by sateeshperi** [comment]
could this be related to #268 ?

**Comment by fellen31** [comment]
Looks like it, sharding on Github vs no sharding locally. This is probably closed by #268.

**Comment by lukfor** [comment]
Should be fixed in 0.9.2
