### ISSUE TITLE
nf-test with custom plugin gets killed halfway when asserting results

### ISSUE THREAD

**Issue by AlexVCaron** [askimed/nf-test#251]
I'm using a custom plugin with nf-test right now, to capture md5sum from complex data (Nifti-gz, it require a dedicated reader to get consistent md5 from the data inside the file). Nifti being a ND-image format, processing can get quite intensive and RAM can get filled before the Java garbage collector has time to pass.

I was wondeing why my tests tend to get killed halfway. Note I am working in a container and docker enforces resource limits, but I hadn't configured anything that could potentially go over those. Then I discovered the infamous **line 54** in the **nf-test** executable, where there is a `-Xmx10g`, and I don't have that much RAM. I changed the value to a lower one - 6g in my case - and it works !

Now it's quite a pain to go and change that line everytime the executable changes. Would it be possible to add an option to set that value ? Or default to a standard **java** way of setting it like the JAVA_TOOL_OPTIONS or something ?

**Comment by lukfor** [comment]
Thanks. This issue has been fixed in PR #264 and will be available in the next update.

btw: are you interested in listing your nf-test plugin (https://github.com/AlexVCaron/nft-nifti) on the plugins page at https://plugins.nf-test.com/?

**Comment by AlexVCaron** [comment]
I completely missed this comment. The plugin is still quite **in-dev**, so are the resources behind it. But we are still supporting it and I would be happy to list it, if it is worth for the community in its current state.
