### ISSUE TITLE
Allow multiple workflows in one test file

### ISSUE THREAD

**Issue by nvnieuwk** [askimed/nf-test#27]
Hi, thanks for creating this awesome tool! I'm currently in the process of creating an `nf-test` prototype for the [nf-core/modules](https://github.com/nf-core/modules) repository and have come across some small issues and improvement suggestions:

- To test the modules (which are processes) we use a workflow that consists of the module we want to test (and usually some other modules too, to create the input data for the desired module). The original input data is defined like [this](https://github.com/nf-core/modules/blob/cc980fb6f3931cb02fbae41ebd0cece34c7638f4/tests/modules/nf-core/bcftools/concat/main.nf#L9-L14), which usually means that the `when` clause in the test file is empty. `nf-test` throws an error if there is no `when` clause (`java.lang.NullPointerException`). Is it possible to make the `when` clause not a mandatory option when using `nextflow_workflow`?

- Similar to the previous issue: A `nextlow_workflow` needs an output, but our testing workflow doesn't actually have any output (we test the files created in an output directory). Is it also possible for `emit` to be optional when using `nextflow_workflow`?

- Because a test is defined as a separate workflow in the current tests, it would be helpful if you could add the ability to be able to use multiple workflows in one test file? (similar to how multiple functions can be tested in one file (https://code.askimed.com/nf-test/testcases/nextflow_function/#multiple-functions))

I hope these won't be an issue to add

Cheers,
Nicolas

**Comment by nvnieuwk** [comment]
Thanks for releasing the solution to this issue so fast! I'll give it a go tomorrow morning :)

**Comment by lukfor** [comment]
Hi Nicolas! 👋

Thank you for giving nf-test a chance! 🙏

> * To test the modules (which are processes) we use a workflow that consists of the module we want to test (and usually some other modules too, to create the input data for the desired module). The original input data is defined like [this](https://github.com/nf-core/modules/blob/cc980fb6f3931cb02fbae41ebd0cece34c7638f4/tests/modules/nf-core/bcftools/concat/main.nf#L9-L14), which usually means that the `when` clause in the test file is empty. `nf-test` throws an error if there is no `when` clause (`java.lang.NullPointerException`). Is it possible to make the `when` clause not a mandatory option when using `nextflow_workflow`?

That makes sense! `when` is now optional.

> * Similar to the previous issue: A `nextlow_workflow` needs an output, but our testing workflow doesn't actually have any output (we test the files created in an output directory). Is it also possible for `emit` to be optional when using `nextflow_workflow`?

That was already fixed, but not yet released. Should work now in 0.6.1.

> * Because a test is defined as a separate workflow in the current tests, it would be helpful if you could add the ability to be able to use multiple workflows in one test file? (similar to how multiple functions can be tested in one file (https://code.askimed.com/nf-test/testcases/nextflow_function/#multiple-functions))
> 

Great suggestion! You can now override `workflow` for each test. Example: https://github.com/askimed/nf-test/blob/main/test-data/workflow/multi/trial.nf.test

----

I just released version 0.6.1. It includes your suggestions. Hope this helps!

Happy Hackathon!

Best, Lukas.

**Comment by lukfor** [comment]
I added now the `expect` keyword to workflow tests. So you can write your workflow tests in the same way as this pipeline test here: https://github.com/askimed/nf-test/blob/main/example/hello.nf.test
Its maybe easier to read as a `then` without `when` . 

This feature is available in the next release.

**Comment by nvnieuwk** [comment]
Awesome! Thanks @lukfor
