### ISSUE TITLE
Suggestions from `nf-core`

### ISSUE THREAD

**Issue by nvnieuwk** [askimed/nf-test#29]
Hi again,

After a discussion in the `nf-core` community we came up with a couple more suggestions that could make incorporation of `nf-test` into `nf-core/modules` a bit easier to implement.

1. Could it be possible to supply a `.yaml` file with the assertions (a bit similar to how it is done in `pytest` => e.g. this [file](https://github.com/nf-core/modules/blob/master/tests/subworkflows/nf-core/fastq_align_dna/test.yml)). 
2. Could it also be possible to add a `tag` system (similar to `pytest --tag`). This would make it easier to run the needed tests on Github Actions instead of having to supply the whole file path.

Cheers,
Nicolas

**Comment by Emiller88** [comment]
Awesome stuff! I'm really excited to get this into nf-core/modules! Do you have anything you can share about the road map for tags? I know we can use pytest-workflow to run nf-test just like we do nextflow right now, but I'd love to cut out the extra dependancy and migrate to nf-test in one move.

So I guess I'm just asking is it a few weeks off, before 2023, before or after March 2023 (our next hackathon which would be a good time to migrate).

**Comment by nvnieuwk** [comment]
Thanks @lukfor! I'll have a look when I got some free time and will surely let you know if we encounter any problems. Thanks for the nice addition :partying_face:

**Comment by nvnieuwk** [comment]
Hi, I've been trying out the new `snapshots` feature for a little bit and found one small issue. It won't run the snapshot test in the following example and I get no warning or error telling me what I did wrong. 

```
nextflow_pipeline {

    name "Tests of the pipeline with all optional parameters on default"
    script "main.nf"

    test("Success") {

        expect {
            assert workflow.success
            assert snapshot(
                workflow,
                path("${outputDir}/families/Proband_12345/reports/Proband_12345.TsTv.count"),
                path("${outputDir}/families/Proband_12345/reports/Proband_12345.bcftools_stats.txt"),
                file("${outputDir}/families/Proband_12345/reports/Proband_12345.TsTv.qual").exists(),
                path("${outputDir}/families/Proband_12345/reports/Proband_12345.FILTER.summary"),
                path("${outputDir}/families/Proband_12345/Proband_12345.vcf.gz").linesGzip[68],
                file("${outputDir}/families/Proband_12345/Proband_12345.vcf.gz.tbi").exists(),
                file("${outputDir}/multiqc_reports/multiqc_report.html").exists(),
                path("${outputDir}/individuals/NA24385/NA24385.g.vcf.gz").linesGzip[53],
                file("${outputDir}/individuals/NA24385/NA24385.g.vcf.gz.tbi").exists(),
                path("${outputDir}/individuals/NA12878/NA12878.g.vcf.gz").linesGzip[53],
                file("${outputDir}/individuals/NA12878/NA12878.g.vcf.gz.tbi").exists()
            )
        }
    }
}
```

This test checks for:
 - md5sum of files that stay consistent during multiple runs
 - the existence of files that differ during multiple runs and cannot be read using `linesGzip`
 - the presence of a line in a file if the file is variable but has some constants

Is it possible to implement a bit of error handling if invalid snapshots creation is attempted? I'll be happy to put this in a different issue if you would prefer it.

Cheers,
Nicolas

**Comment by lukfor** [comment]
You created the `snapshot` but you forgot to execute the `match()` method to compare it with the saved snapshot.

However, I agree with you that we need a better error reporting for that case.

**Comment by lukfor** [comment]
> Awesome stuff! I'm really excited to get this into nf-core/modules! Do you have anything you can share about the road map for tags? I know we can use pytest-workflow to run nf-test just like we do nextflow right now, but I'd love to cut out the extra dependancy and migrate to nf-test in one move.
> 
> So I guess I'm just asking is it a few weeks off, before 2023, before or after March 2023 (our next hackathon which would be a good time to migrate).

Thanks. We plan to release this feature in the next version in about 2-3 weeks.

**Comment by jfy133** [comment]
I'm not sure if we should keep a thread of all the nf-core requests here rather than seaprate issues, but just in case x-ref: https://github.com/askimed/nf-test/issues/43

**Comment by Emiller88** [comment]
Maybe a tag for nf-core? I think new issues should be made, rather than just trying to keep track of what we want in one long thread.

**Comment by nvnieuwk** [comment]
> You created the `snapshot` but you forgot to execute the `match()` method to compare it with the saved snapshot.
> 
> However, I agree with you that we need a better error reporting for that case.

Thanks! :partying_face:

**Comment by lukfor** [comment]
> Maybe a tag for nf-core? I think new issues should be made, rather than just trying to keep track of what we want in one long thread.

Thanks for your suggestion. We created a `nf-core` label and it would help us if you can create separate issues.

**Comment by Emiller88** [comment]
@lukfor Can we change the color of the label to `#24B064`?

**Comment by lukfor** [comment]
Tags moved to #49
