### ISSUE TITLE
Extending PATH with bin/ when testing processes

### ISSUE THREAD

**Issue by birnbera** [askimed/nf-test#31]
Hi @lukfor, thanks again for the great work on this. I encountered what I believe is a bug in the way Nextflow is invoked when running process-level tests. In my case, I have scripts in `bin/` that Nextflow automatically adds to the `PATH` at runtime. When testing a process that calls one of the scripts in `bin/`, it fails because it can't find the script on the `PATH` but only when testing an individual process. When testing workflows and pipeline runs it works fine. It appears that the `mock.nf` generated for the test is invoked from a different directory than the one specified by `$baseDir` (the value of which is as expected). As such, it is not possible for me to test processes that invoke custom scripts.

I'm currently running `nf-test@0.6.0` in case this has been fixed in one of the recent releases.

**Comment by lukfor** [comment]
Hi! Thanks! 

This issue should be fixed in version 0.6.2.
