### ISSUE TITLE
Feature request: github ci workflow

### ISSUE THREAD

**Issue by matthdsm** [askimed/nf-test#38]
Hi,

Would you be able to add a "recommended" github CI workflow example to run nf-test on github actions?
Alternatively, would you be able to add a dedicated action?

Thanks
M

**Comment by Emiller88** [comment]
Here's an example! https://github.com/nf-core/methylseq/blob/5893122512add5350e4d9e3235b8e2fb500e5679/.github/workflows/ci.yml

**Comment by lukfor** [comment]
There is now a tutorial about running nf-test on GitHub: https://www.nf-test.com/tutorials/github-actions/
