### ISSUE TITLE
Feature request: autogenerate assertions

### ISSUE THREAD

**Issue by matthdsm** [askimed/nf-test#39]
Hi,

Would it be possible to add a function to auto generate assertions for a test?
e.g. we define a test and then run `nf-test create-assertions`, which would output `size()` and `checksum` assertions for example.

Thanks

**Comment by lukfor** [comment]
Hi!

First of all, thank you for maintaining the bioconda recipe! 🙏

We are currently working on snapshot testing (similar to https://jestjs.io/docs/snapshot-testing). A snapshot contains the content of a channel and the checksum for files. The first time this test is run, nf-test creates a snapshot file. The features is already implemented, but we need some more testing. However, it is the next feature we are planing to deploy. You could find more information and examples here:
https://github.com/askimed/nf-test/blob/features/snapshots/docs/assertions/snapshots.md

The snapshot file itself is a json file, an example is here:
https://github.com/askimed/nf-test/blob/features/snapshots/test-data/process/path-util/test_process.nf.test.snap

This could be an alternative to auto generated assertions.

**Comment by matthdsm** [comment]
Awesome, works for me 😄 
Thanks, looking forward to the next version!
