### ISSUE TITLE
Nevermind

### ISSUE THREAD

**Issue by willburden** [askimed/nf-test#40]
Hi! I have a file named `Util.groovy` which contains functionality I would like to share between tests. According to the documentation, placing this file in the `lib` directory allows it to be accessed from within the `then` block — very nice!

However, I would like to use some of the util methods to prepare the environment before running the tested process (e.g. creating a temporary directory to write the results to). I have tried calling them from various scopes: inside the `when` block, within the `test()` block before the `when`, at the very top of the file; `Util` doesn't seem to be available to code at any other point in the `.nf.test` file.

Explicitly `import`ing the class doesn't resolve either. Perhaps this is a problem with the classpath but I can't find a way to change the classpath.

Is there any way to achieve what I'm trying to do here?

Update: immediately after posting this I see that the documentation lists this feature as experimental... My bad

**Comment by lukfor** [comment]
Hi! sorry for the confusion! We just released nf-test 0.7.0 and in this release everything should work as documented.
