### ISSUE TITLE
Bug Report: Generating  Multiple Process from the same File

### ISSUE THREAD

**Issue by vasquini** [askimed/nf-test#47]
I have a file, main.nf, with many processes for a pipeline. I ran: 
`nf-test generate process main.nf`
and I got the following. Notice that main.process and main.fastq.nf.test are one file called "main. process main.fastq.nf.test" but I think should be separate files.
![image](https://user-images.githubusercontent.com/82479384/199750738-03d44e56-7d3d-4001-8b0e-e0a53951b5f9.png)

**Comment by lukfor** [comment]
Thank you!

I think the following comment on [line 369 ](https://github.com/vasquini/EDLB-micropipe/blob/10a1f25306901659149fbc1f12a7f14961a20409/Dev-micropipe4/main.nf#L396) in your `main.nf` file could be a problem for the `nf-test generate` command.

Could you try to remove it? I will fix this bug in the next release 👍

**Comment by vasquini** [comment]
Thanks so much! Removing the comment fixed this issue.
