### ISSUE TITLE
MissingPropertyException Issue

### ISSUE THREAD

**Issue by vasquini** [askimed/nf-test#48]
I generated the process through `nf-test generate process main.nf` where main.nf has multiple processes and the file I'm working on is called "main.basecalling.nf.test". I have been trying to get the input into this process by using Channel.fromPath() and file() but it always results in the following error:
groovy.lang.MissingPropertyException: No such property: Channel for class: com.askimed.nf.test.lang.TestContext

The way I try to input is:
`input[0] = Channel.fromPath("${params.fast5}", checkIfExists:true)` where fast5 is a path declared in the params section. This worked for me on a very simple process that used the same tool, Guppy. But it doesn't work here. Another thing I tried was `input[0] = file("${params.fast5}")` and I received the exact same error messafe.

**Comment by lukfor** [comment]
Hi!
Could you please share the whole nf.test script with me?

It seems that you forgot the `"""` in the `process` block. Example:

```
process {
  """
  input[0] = Channel.fromPath("${params.fast5}", checkIfExists:true
  """
}
```

The process mapping has to be a multi-line string, because this code is executed by Nextflow.

**Comment by vasquini** [comment]
That might fix my issue. I will try that. I mistook it for some sort of comment, and my working process is within the """. Thanks!
