### ISSUE TITLE
Feature Request: Add tag system

### ISSUE THREAD

**Issue by lukfor** [askimed/nf-test#49]
@nvnieuwk:

>  Could it also be possible to add a tag system (similar to pytest --tag). This would make it easier to run the needed tests on Github Actions instead of having to supply the whole file path.

See #29

**Comment by lukfor** [comment]
This features was released in [v0.7.3](https://github.com/askimed/nf-test/releases/tag/v0.7.3) 🚀

**Comment by nvnieuwk** [comment]
Awesome! Thank you! 🥳
