### ISSUE TITLE
Support for `linesGzip` in snapshots

### ISSUE THREAD

**Issue by nvnieuwk** [askimed/nf-test#58]
Hi,

Is it possible to add support for `linesGzip` to snapshots? In some cases `md5sums` differ and a simple `path` snapshot is not possible to use. It would be helpful if I could supply a line number or numbers that the snapshot needs to check for. 

Suggestion:
```
assert snapshot(
     workflow,
     path("${outputDir}/file_1").linesGzip[68],
     path("${outputDir}/file_2").linesGzip[1..15]
).match()
```

Cheers,
Nicolas

**Comment by fmalmeida** [comment]
Hello,
Dropping in to say that this feature would indeed be really appreciated.

**Comment by zichner** [comment]
Hi.
I also want to support this feature request. Since the majority of pipeline output files are usually gzipped for file size reasons it would be really great if snapshots would work for gz files as well.
I think this is currently the most important missing feature in nf-test.
Thanks for all the work!

**Comment by seppinho** [comment]
Hi guys, the latest nf-test release now includes an improved version of manipulating gz files. See here: https://code.askimed.com/nf-test/assertions/files/

@nvnieuwk your initial example would already have worked before, but we suggest to remove the workflow object (includes hashes) and only include e.g. worklow.success. Anyways, the new grep command might helps as well in future.

**Comment by fmalmeida** [comment]
Thank you!
That looks really neat!
Awesome work. Really cool tool.

I'll be closing the issue :)

**Comment by nvnieuwk** [comment]
Thank you very much!!!
