### ISSUE TITLE
Feature request: nextflow options

### ISSUE THREAD

**Issue by matthdsm** [askimed/nf-test#73]
Hi,

Would it be possible to add an option to modify the nextflow command?
I'd like to be able to add stuff like `dump-channels` to the command line to make debugging easier

Thanks
M

**Comment by ewels** [comment]
A generic way to customise the Nextflow command would also solve https://github.com/askimed/nf-test/issues/71

**Comment by lukfor** [comment]
Great idea! We will definitely add this feature 👍

**Comment by lukfor** [comment]
This features was released in [v0.7.3](https://github.com/askimed/nf-test/releases/tag/v0.7.3) 🚀
