### ISSUE TITLE
Bug: cannot import class from jar file in /lib

### ISSUE THREAD

**Issue by Afollet** [askimed/nf-test#74]
Hi,

I have a jar file from the built project https://github.com/ssadedin/groovy-ngs-utils

This jar is placed in the `./lib` directory reference by my projects `nf-test.config`. I want to use this jar in my tests.

I would like to use a line like this in the Then {} block like so:

```
 def vcf = VCF.parse("$baseDir/tests/test_data/NA12879.vcf.gz")
```

However, when I add this statement:
```
import gngs.VCF
```

I recieve the error:
```
Error: org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
/home/alex/vcgs/repipe/src/tests/generate_denovo_rate.nf.test: 1: unable to resolve class gngs.VCF
 @ line 1, column 1.
   import gngs.VCF
```

However, if I import everything I receive no error:
```
import gng.*
```   

Then my code in the `then` block errors:
```
  groovy.lang.MissingPropertyException: No such property: VCF for class: com.askimed.nf.test.lang.TestContext
 ```
 
 I am certain the class VCF exists and gngs.VCF is a valid way to import it. 
 
 Please advise

**Comment by seppinho** [comment]
Hi,
please specifiy the path to the lib on the command line like this:
`--lib groovy-ngs-utils/build/libs/groovy-ngs-utils.jar`

**Comment by lukfor** [comment]
Thanks for testing it with `groovy-ngs-utils`. We added an example to the [documentation](https://code.askimed.com/nf-test/assertions/libraries/#using-local-jar-files) that shows also how to set the jar in the `nf-test.config` file.

Feel free to reopen this issue when you encounter problems.
