### ISSUE TITLE
Is it possible to have dummy output

### ISSUE THREAD

**Issue by Khushbu04in** [askimed/nf-test#8]
I want to test a workflow but it has multiple steps. I don't want to test everything in one shot. Is is possible to create some output files and nf-test just run portion for which files are not available (similar to nextflow)

**Comment by seppinho** [comment]
Hi there,
Thanks for giving nf-test a try. With nf-test you can test (a) processes, (b) workflows and (c) complete pipelines. In case you're using DSL2 modules, see here for some examples how to run nf-test on individual modules: https://github.com/askimed/nf-test-examples/tree/main/tests/modules/local
