### ISSUE TITLE
Support for `-resume` ?

### ISSUE THREAD

**Issue by glormph** [askimed/nf-test#83]
I have some fairly slow pipeline tests (even with "small" test data) which take minutes, running in a bash script. Some of the tests are similar to another test and have overlapping steps. When testing by hand I use `-resume` a lot. I understand that in general it is good to start tests "clean", but I wondered if nf-test could support using `-resume` (and I have neither found if it is already possible, nor a way to activate it in NF config unfortunately).

I'm not an experienced tester, so maybe this is a bad idea in general. Maybe I should split into workflows for the tests that have identical first steps, so I only test them once. But for longer tests it'd make the development feedback loop shorter.

**Comment by seppinho** [comment]
Hi there,
Per design nf-test allways starts with a clean work directory, so your use case is currently not supported.

Fyi, the latest nf-test release allows you to specify other Nextflow options (like `-dump-channels`). See here: https://code.askimed.com/nf-test/getting-started/#nextflow-options

**Comment by glormph** [comment]
Thanks, I understand. I'll keep an eye out if this'd ever show up on your roadmap :) I'm just starting with testing pipelines, so I'll try and see if I can work around my particular problem.

**Comment by Truongphikt** [comment]
In my use case, I use nf-test to develop and test a sub-workflow simultaneously. `nf-test` helps me design custom minimal input channels separate from the main script, it saves time and resources. But if in sub-workflow had some long-run process, I have to re-run every time. I think it will be convenient if we have the `-resume` option when running the nf-test with sub-workflow.
