### ISSUE TITLE
Command 'ps' required by nextflow to collect task metrics cannot be found

### ISSUE THREAD

**Issue by noepozzan** [askimed/nf-test#9]
Hi,

nf-test looks like a very nice tool. I wanted to test a nextflow pipeline with singularity containers.
Since most containers do not have "ps" installed, the tests don't pass.
Is there a way to run the tests without "ps" or are you aware of any other way to make this work?

Thank you!

**Comment by seppinho** [comment]
Thanks, the latest version now includes a command-line parameter (`--without-trace`) and a nf-test.config option to disable it for all runs (`withTrace = false`). Let us know if this works for you.

**Comment by noepozzan** [comment]
Oh, that sounds good. Thanks, I'll try it and let you know.

**Comment by lukfor** [comment]
I mark this issue as solved.
