### ISSUE TITLE
mvn install fails on tests

### ISSUE THREAD

**Issue by fbreitwieser** [askimed/nf-test#90]
Hi developers, 

I'm just testing nf-test, thanks a lot for your development! 

The local compilation with mvn works well and I can get the JAR when I disable the tests. However, I've a couple of failures in the tests:

### With no NXF_VER or NXF_VER=23.04.1

23 failures in total, 19 failures of workflows stating "Nextflow DSL1 is no longer supported. Update your script to DSL2, or use Nextflow 22.10.x or earlier".

### With NXF_VER=22.10.4

Still got 11 different failures, I looked at three below due to ordering, some assertion and MacOS-specific message.

````
   Test [ab55e44f] 'Should create 5 output files' FAILED (2.023s)

   java.lang.RuntimeException: Different Snapshot:
````
<img width="789" alt="image" src="https://github.com/askimed/nf-test/assets/516060/10c1043d-3426-4062-90da-17e3b1ac3aad">

````
   Test [e1214927] 'Test from an other testsuite' FAILED (1.862s)

   Assertion failed:

   assert 22 == 21
             |
             false
````

```
   Test [ab55e44f] 'Should create 5 output files' FAILED (1.796s)

   java.lang.RuntimeException: Different Snapshot:
```

<img width="1527" alt="image" src="https://github.com/askimed/nf-test/assets/516060/1de80c19-9494-4257-a630-bcd3f67e1ab9">

Full logs are attached
[mvn-install-no-NXF_VER.log](https://github.com/askimed/nf-test/files/11601427/mvn-install-no-NXF_VER.log)
[mvn-install-v23.04.1.log](https://github.com/askimed/nf-test/files/11601428/mvn-install-v23.04.1.log)
[mvn-install-v22.10.log](https://github.com/askimed/nf-test/files/11601429/mvn-install-v22.10.log)

**Comment by lukfor** [comment]
Thanks for trying nf-test and reporting this issue.
It looks like a combination between MacOS and different Nextflow version. We will try to make these testcases more generic.

**Comment by lukfor** [comment]
Thank you, Florian. With the latest release, we have removed support for DSL1 and fixed the remaining test cases. Now, `mvn install` works on both macOS and Linux.

Please feel free to reopen this issue if you encounter any other related problem.
