### ISSUE TITLE
Implement soft `config` & `profile` override settings in nf-test

### ISSUE THREAD

**Issue by sateeshperi** [askimed/nf-test#94]
Problem Statement:

In the process of integrating nf-test into GitHub Actions (GHA) CI, we've identified a limitation concerning the specification of running profiles (e.g., docker, singularity, conda) in test files. Currently, these profiles have to be hardcoded, which reduces flexibility and adaptability in CI job matrix.

Proposed Solution:

We propose the implementation of soft configuration/profile overrides for nf-test. This functionality would mimic that of nextflow's `-c` option, which appends new configuration settings to the default configuration in an additive manner.

Implementing this feature would allow us to specify profiles dynamically within the CI job matrix, streamlining the testing process and offering improved adaptability in various testing environments.

Impact:

This feature would significantly enhance nf-test's versatility, making it more convenient and flexible for integration with various CI/CD pipelines, especially in complex, multi-environment settings.

We're keen on any feedback or alternative suggestions you may have about this proposal. Thank you for your attention to this matter.

**Comment by lukfor** [comment]
thanks for trying nf-test!

You could try to overwrite the default profile with the `--profile` flag. This feature is currently undocumented. If this solves your problem, we will add it to the documentation.

Example:

```
nf-test test --profile conda
```

**Comment by sateeshperi** [comment]
@lukfor overwrite of the profile is what I am trying to avoid and rather have a soft-override which appends rather than hard-overwrite. thoughts ?

**Comment by sateeshperi** [comment]
and the use of `--profile` via CLI is covered [here](https://code.askimed.com/nf-test/cli/test/#-profile-nextflow_profile)

**Comment by lukfor** [comment]
PR #128 addresses this issue and introduces the following behavior. Happy to hear your feedback 🙌

----

### Basic Profile Usage

By default, `nf-test` reads the profile configuration from `nf-test.config`. If you've defined a profile called `A` in `nf-test.config`, running `nf-test --profile B` will start Nextflow with only the `B` profile. It replaces any existing profiles.

### Combining Profiles with "+"

To combine profiles, you can use the `+` prefix. For example, running `nf-test --profile +B` will start Nextflow with both `A` and `B` profiles, resulting in `-profile A,B`. This allows you to extend the existing configuration with additional profiles.

### Profile Priority Order

Profiles are evaluated in a specific order, ensuring predictable behaviour:

1. **Profile in nf-test.config:** The first profile considered is the one defined in `nf-test.config`.

2. **Profile Defined in Testcase:** If you specify a profile within a testcase, it takes precedence over the one in `nf-test.config`.

3. **Profile Defined on the Command Line (CLI):** Finally, any profiles provided directly through the CLI have the highest priority and override/extends previously defined profiles.

**Comment by sateeshperi** [comment]
just what we need...thanks @lukfor 👍

**Comment by lukfor** [comment]
Perfect. I will merge it tomorrow and we will create a release before the Hackathon 🙌
